 this.headersLoaders = [
      'ФИО',
      '№ Склада',
      'График работы',
      '№ транспорта',
      'Активность',
    ];


this.loaders = [
      {
        fullName: 'Иванов Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Кукин Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Сидоренко Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Капалкин Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Шарапов Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Питьков Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Иванов Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Кукин Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Сидоренко Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Капалкин Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Шарапов Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
      {
        fullName: 'Питьков Иван Иванович',
        warehouseNumber: '1',
        schedule: 'Пн-Пт 9:00-18:00',
        transportNumber: 'A 123 AA 77',
        isActive: true,
      },
    ];
