 this.transport = [
      {
        model: 'Mercedes-Benz',
        number: 'A 123 AA 77',
        type: 'Газель',
        volume: '4.5',
        loadCapacity: '1.5',
        city: 'Москва',
        isActive: true,
        schedule: 'Пн-Пт 9:00-18:00',
        hasDriver: true,
      },
      {
        model: 'Ford Transit',
        number: 'B 234 BB 88',
        type: 'Грузовик',
        volume: '6.0',
        loadCapacity: '2.5',
        city: 'Санкт-Петербург',
        isActive: false,
        schedule: 'Пн-Пт 8:00-20:00',
        hasDriver: false,
      },
      {
        model: 'Volkswagen Crafter',
        number: 'C 345 CC 99',
        type: 'Минивэн',
        volume: '5.0',
        loadCapacity: '1.2',
        city: 'Новосибирск',
        isActive: true,
        schedule: 'Сб-Вс 10:00-16:00',
        hasDriver: true,
      },
      ]
